use_frameworks!

source 'git@github.com:CocoaPods/Specs.git'
source 'git@github.com:budulayreturns/DSHFirstPrint-Spec.git'
source 'git@github.com:budulayreturns/DSHSecondPrint-Spec.git'

platform :ios, '11.0'

target 'DSHFirstPrintPod_Example' do
  pod 'DSHFirstPrintPod', :path => '../'
  pod 'DSHSecondPrintPod'
  
  target 'DSHFirstPrintPod_Tests' do
    inherit! :search_paths

    
  end
end
